### ISSUE TITLE
Bug: can cause IndexOutOfBoundsException on some cases

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [klinker41/android-chips#22]
Not sure about how to reproduce it, but if you play with it enough, you can get this exception.

Here's the log:

08-22 13:05:36.751  22900-22900/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.android.ex.chips.sample, PID: 22900
    java.lang.IndexOutOfBoundsException: Invalid index 1, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.android.ex.chips.BaseRecipientAdapter.isEnabled(BaseRecipientAdapter.java:1004)
            at android.widget.ListView.dispatchDraw(ListView.java:3363)
            at android.view.View.draw(View.java:16206)
            at android.widget.AbsListView.draw(AbsListView.java:5984)
            at android.view.View.updateDisplayListIfDirty(View.java:15126)
            at android.view.View.getDisplayList(View.java:15149)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
            at android.view.View.updateDisplayListIfDirty(View.java:15086)
            at android.view.View.getDisplayList(View.java:15149)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2751)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2584)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2176)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
            at android.view.Choreographer.doCallbacks(Choreographer.java:590)
            at android.view.Choreographer.doFrame(Choreographer.java:560)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by klinker24** [comment]
Fixed with: https://github.com/klinker41/android-chips/commit/dbae86c0189e4adca707007ebd2a6d805e9f7be2
